spring:
  profiles:
    active: "dev"

---

server:
  port: 8090
         
# ===============================
# = Hibernate datasource
# ===============================
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/parking
    username: alejandro.gomez@ceiba.com.co
    password: AGH821102

# ===============================
# = JPA configurations
# ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      
# ===============================
# = Logging configurations
# ===============================
logging:
  level:
    root: WARN
    com.memorynotfound: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO

---

server:
  port: 8090
  
# ===============================
# = H2 data source
# ===============================
spring:
  profiles: test
  datasource:
    url: jdbc:h2:~/parking2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: alejandro.gomez
    password:

# ===============================
# = JPA configurations
# ===============================
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    openInView: false
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      #naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    properties:
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true